sudo: required
services:
  - docker

before_install:
  - docker build -t alexisgf/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true alexisgf/react-test npm run test -- --coverage

after_success:
  - docker build -t alexisgf/multi-client ./client
  - docker build -t alexisgf/multi-nginx ./nginx
  - docker build -t alexisgf/multi-server ./server
  - docker build -t alexisgf/multi-worker ./worker
  #Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #Take those images and push them to docker hub
  - docker push alexisgf/multi-client
  - docker push alexisgf/multi-nginx
  - docker push alexisgf/multi-server
  - docker push alexisgf/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "multi-docker"
  env: "Multidocker-env"
  bucket_name: "elasticbeanstalk-us-east-2-753381016673"
  bucket_path: "multi-docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY